### ISSUE TITLE
Unknown Message

### ISSUE THREAD

**Issue by rickklaasboer** [rickklaasboer/wego-overseer#310]
```
2024-01-29T22:44:38.646Z 50 name=wego-overseer hostname=919e2be663e1 pid=80 msg=Failed to execute event KarmaUpvoteEvent [
  DiscordAPIError[10008]: Unknown Message
      at handleErrors (/app/node_modules/@discordjs/rest/dist/index.js:640:13)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async SequentialHandler.runRequest (/app/node_modules/@discordjs/rest/dist/index.js:1021:23)
      at async SequentialHandler.queueRequest (/app/node_modules/@discordjs/rest/dist/index.js:862:14)
      at async REST.request (/app/node_modules/@discordjs/rest/dist/index.js:1387:22)
      at async MessageManager._fetchSingle (/app/node_modules/discord.js/src/managers/MessageManager.js:102:18) {
    requestBody: { files: undefined, json: undefined },
    rawError: { message: 'Unknown Message', code: 10008 },
    code: 10008,
    status: 404,
    method: 'GET',
    url: 'https://discord.com/api/v10/channels/943969948768809022/messages/1201659169732821033'
  }
] v=0
```

**Comment by Joehoel** [comment]
Thanks for the quality issue

**Comment by rickklaasboer** [comment]
Seems the be an edge case, closing for now.
